/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Tests;

interface Counter {
    public int value();
    public Counter advance();
}

class FunctionalCounter implements Counter {
    int i;
    public FunctionalCounter(int start, ImperativeCounter ic) {
        i = start;
        ic.i += 1;
    }
    public FunctionalCounter(int start) {
        i = start;
    }
    public int value() { return i; }
    public Counter advance() {
        return new FunctionalCounter(i+1);
    }
    public void testing(ImperativeCounter ic) {
        ic.i = 10;
    }
}

class ImperativeCounter implements Counter {
    int i;
    ImperativeCounter(int start) {
        i = start;
    }
    public int value() { return i; }
    public Counter advance() {
        i = i+1;
        return this;
    }
}

public class App {
    public static void test(Counter c1, Counter c2) {
        System.out.println(String.format("%s %s", c1.value(), c2.value()));
    }
    public static void main(String[] args) {
        Counter fc = new FunctionalCounter(0);
        test(fc, fc.advance());
        Counter ic = new ImperativeCounter(0);
        test(ic, ic.advance());
        ((FunctionalCounter)fc).testing((ImperativeCounter)ic);
        Counter fc2 = new FunctionalCounter(0,(ImperativeCounter)ic);
        ((ImperativeCounter)ic).i += 1;
    }
}